/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GroupProps, useFrame } from '@react-three/fiber';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import { AnimationMixer, Object3D } from 'three';
import { SkeletonUtils } from '../../utils/SkeletonUtils';

const MODEL_URL =
  'https://ravers-models.s3.us-east-2.amazonaws.com/RAVERz_AVATARzGREETERCOMPRESS.glb';

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial002_Baked: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ['defaultMaterial.002_Bake1_baked']: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | 'greeter leaning on a wall'
  | 'greeter stop walk'
  | 'greeter talking'
  | 'greeter walking'
  | 'greeter yelling';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

type ModelProps = {
  animation?: ActionName;
  duration?: number;
} & GroupProps;

export default function GreeterModel(props: ModelProps) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations, scene } = useGLTF(
    MODEL_URL
  ) as GLTFResult;

  Object.values(materials).forEach((material) => (material.skinning = true));
  const [mixer, setMixer] = useState<AnimationMixer | undefined>();
  const actions = useRef<GLTFActions>();

  useEffect(() => {
    const model = SkeletonUtils.clone(scene.children[0]) as Object3D;

    model.traverse((obj) => (obj.frustumCulled = false));
    const _mixer = new AnimationMixer(model);

    // @ts-ignore
    actions.current = animations.reduce((acc, cur) => {
      const name = cur.name as ActionName;
      // @ts-ignore
      acc[name] = _mixer.clipAction(cur, group.current);
      return acc;
    }, {});

    // @ts-ignore
    actions.current['greeter leaning on a wall'].play();

    setMixer(_mixer);
  }, []);

  useFrame((_, delta) => {
    mixer && mixer.update(delta);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, 0, 2.42]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0065}
      >
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.defaultMaterial002_Baked.geometry}
          material={materials['defaultMaterial.002_Bake1_baked']}
          skeleton={nodes.defaultMaterial002_Baked.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_URL);
