/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import { AnimationMixer, Object3D } from 'three';
import { SkeletonUtils } from '../../utils/SkeletonUtils';

type GLTFResult = GLTF & {
  nodes: {
    Female_1001_MBLab_human_female004_Baked: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ['Female_1.001_MBLab_human_female.004_Bake1_baked']: THREE.MeshStandardMaterial;
  };
};

type ActionName = 'Armature|mixamo.com|Layer0.006';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

const MODEL_URL =
  'https://ravers-models.s3.us-east-2.amazonaws.com/RAVERz_AVATARzDJCOMPRESS.glb';

export default function DJModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations, scene } = useGLTF(
    MODEL_URL
  ) as GLTFResult;

  Object.values(materials).forEach((material) => (material.skinning = true));
  const actions = useRef<GLTFActions>();
  const [model, setModel] = useState<Object3D | undefined>();
  const [mixer, setMixer] = useState<AnimationMixer | undefined>();

  useEffect(() => {
    const sceneClone = SkeletonUtils.clone(scene) as Object3D;
    const _model = sceneClone.children[0];

    _model.traverse((obj) => (obj.frustumCulled = false));
    const _mixer = new AnimationMixer(_model);

    // @ts-ignore
    actions.current = animations.reduce((acc, cur) => {
      const name = cur.name as ActionName;
      // @ts-ignore
      acc[name] = _mixer.clipAction(cur, group.current);
      return acc;
    }, {});

    // @ts-ignore
    actions.current['Armature|mixamo.com|Layer0.006'].play();
    setModel(_model);
    setMixer(_mixer);
  }, []);

  useFrame((_, delta) => {
    mixer && mixer.update(delta);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Armature"
        position={[0, 0, -0.09]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.006, 0.006, 0.006]}
      >
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Female_1001_MBLab_human_female004_Baked.geometry}
          material={
            materials['Female_1.001_MBLab_human_female.004_Bake1_baked']
          }
          skeleton={nodes.Female_1001_MBLab_human_female004_Baked.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_URL);
